### ISSUE TITLE
Atualização do readme.

### ISSUE THREAD

**Issue by fvieir** [leandromarcelino93/menuproject#1]
Ola Leandro, como vai?

Conforme deixado o Feedback e orientações no Discord, segue minha solicitação para atualização do readme.

Qualquer duvida é so chamar.

Forte abraço

**Comment by leandromarcelino93** [comment]
Fala Fabrício, tudo bem? 

Acabei de atualizar, obrigado pelo apoio! 

Abração!

**Comment by fvieir** [comment]
Excelente, obrigado.
